version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
       - ./:/sandbox
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    volumes:
       - ./pgadmin:/root/.pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=1234
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
